### ISSUE TITLE
Include PuTTY license (just to be safe)

### ISSUE THREAD

**Issue by tannerhelland** [wqweto/ZipArchive#1]
The ever-paranoid users at vbforums have raised concerns about PuTTY's licensing model as used in this project:

http://www.vbforums.com/showthread.php?848511-Is-there-a-way-to-work-around-the-Resource-Editor

I tried to keep things civil, but you know how it gets over there...  

Anyway, to keep them happy, maybe it's worthwhile to include an explicit copy of PuTTY's license in the /lib/sshzlib/ folder, since PuTTY's developers are sloppy about including copyright and licensing details in each source file.

(Thanks again for sharing this project!  I hope to test it on parsing ORA files in the near future...)

**Comment by wqweto** [comment]
10x for the tip. Done in 6680e249a8e482cc5a25644d60935f7c59d3e422
