### ISSUE TITLE
ConsolePrint not work correctly on CJK

### ISSUE THREAD

**Issue by jack6th** [wqweto/ZipArchive#15]
I read your answer from stackoverflow [How to make VB6 console application which prints output to the command prompt](https://stackoverflow.com/questions/54181547/how-to-make-vb6-console-application-which-prints-output-to-the-command-prompt)   .    
It works.   
ConsolePrint works on ASCII.  But not work correctly on CJK.   
eg.   
`ConsolePrint("确定" & vbCrLf)`

How to output CJK correctly ?

**Comment by wqweto** [comment]
> How to output CJK correctly ?

Sorry but I no idea.
