### ISSUE TITLE
Zip with password is failed

### ISSUE THREAD

**Issue by cyberzilla** [wqweto/ZipArchive#16]
I have create zip file from folder like code below, the zip file is successfully created, but with no password

```
Dim Zip As New cZipArchive
With Zip
    .AddFromFolder App.Path & "\test\*.*", Recursive:=True, TargetFolder:="test", IncludeEmptyFolders:=True, Password:="test123"
    .CompressArchive App.Path & "\test.zip"
End With
```
Please help @wqweto 

Regards

**Comment by wqweto** [comment]
Crypto support is not enabled by default to reduce class footprint in final executable. In project properties dialog try setting `ZIP_CRYPTO = 1` in conditional compilation setting like this


![image](https://user-images.githubusercontent.com/987963/107000661-ecc1af80-6790-11eb-8288-d0c1ae7bec5b.png)


Keep in mind that by default cZipArchive uses the weaker ZipCrypto encryption to be most compatible with Windows Explorer but this can easily be cracked. You can try setting `EncrStrength` to 1, 2 or 3 for stronger AES based encryption which is compatible with WinZip, 7-zip and almost every other zip utility except Windows Explorer.

**Comment by cyberzilla** [comment]
ow...hahaha, thanks @wqweto
