### ISSUE TITLE
Size of archive exceeds 2GB

### ISSUE THREAD

**Issue by Seniorchef** [wqweto/ZipArchive#17]
Thank you for the code. 

I tested it with the attached sample program with a different .addfromfolder-command in command1 to my testdata (folder with subfolders, 3.5gb of about 3k documents). 

When compressing this folder I get an error -1 "overflow" and the compressing stops. 
Before that error 131 in pvVfsSeek is raised because of a negative lPosition value.

Do you have an idea to solve this issue to compress to archives larger than 2 gb?

**Comment by wqweto** [comment]
Checkout the `ToDo (not supported yet)` section of the repo's README.

This is more complicated that just an error in `pvVfsSeek` as the original ZIP format has a 2GB file size limit.

You might solve this issue by implementing Zip64 support which has different internal structures needed to accomodate for expanded 64-bit file sizes.

**Comment by Seniorchef** [comment]
Hi, Vladimir!

Thanks for your reply -  that was fast! 

So I will change back to your vszlib classes that I used before. They work fine, but I don't understand how to create ZIP-Archives with these classes (that’s why I tried the ZipArchive-Class). Is it just naming the archive ".zip" in the compress-Method?

 

I tried the sample in the Readme, but my result is a 0 byte archive. Do I miss somethong?

Thanks for your efforts

Jo (seniorchef)

 

Von: Vladimir Vissoultchev ***@***.*** 
Gesendet: Donnerstag, 27. Mai 2021 10:19
An: wqweto/ZipArchive
Cc: Seniorchef; Author
Betreff: Re: [wqweto/ZipArchive] Size of archive exceeds 2GB (#17)

 

Checkout the ToDo (not supported yet) section of the repo's README.

This is more complicated that just an error in pvVfsSeek as the original ZIP format has a 2GB file size limit.

You might solve this issue by implementing Zip64 support which has different internal structures needed to accomodate for expanded 64-bit file sizes.

**Comment by wqweto** [comment]
> Do I miss somethong?

You can try `7z.dll` from [version 9.22](https://sourceforge.net/projects/sevenzip/files/7-Zip/9.22/) of 7-zip because newer versions are not tested (and probably not supported).

You can use the `Init` method to initilize the library with the exact `c:\path\to\7z.dll` file with the specific DLL version.

**Comment by Seniorchef** [comment]
Thanks again, Vladimir!

 

I was unclear in my mail: the sample works fine when I name the archive "Sample.7z" and it works not  when I call it "Sample.Zip". 

The dll is in place and found by the routine. I already included the class in my app.

 

But I don't know how to make the class create a zip-archive instead of creating a 7z-archive. I (and my clients) prefer zip-archives. They can be extracted without extra tools (thought 7z is an excellent one). 

It would be fine to have one class to create zip and 7z archives (even better to create zip with more than 2gb). That is what I understood the 7z.dll can do, and that is what I hoped to get from your sample.

 

Regards

Jo

 

Von: Vladimir Vissoultchev ***@***.*** 
Gesendet: Donnerstag, 27. Mai 2021 16:12
An: wqweto/ZipArchive
Cc: Seniorchef; Author
Betreff: Re: [wqweto/ZipArchive] Size of archive exceeds 2GB (#17)

 

Do I miss somethong?

You can try 7z.dll from version 9.22 <https://sourceforge.net/projects/sevenzip/files/7-Zip/9.22/>  of 7-zip because newer versions are not tested (and probably not supported).

You can use the Init method to initilize the library with the exact c:\path\to\7z.dll file with the specific DLL version.

**Comment by wqweto** [comment]
There is a `Create zip file with unicode filenames` section in VszZip repo's README -- I thought you were talking about it when you said "I tried the sample in the Readme, but my result is a 0 byte archive" as there is no other sample that produces ZIP files.

Again, you have to use version 9.22 of the 7z.dll to be able to produce ZIP files. Newer versions of 7z.dll tend to not work well with VszLib and can successfully produce only 7z files.
