### ISSUE TITLE
Unzip a file from subfolder of zip, in a folder without subfolder

### ISSUE THREAD

**Issue by CouinCouin** [wqweto/ZipArchive#21]
Hi wqweto,

Trying to run your app :) Successfully ziped the 3 example files from _C:\TEMP_ (replaces _D:\TEMP_ as well as on the VM I have only C:\ ) to _aaa.zip_ (removed level in the zip filename), with Command_3 sub.
So the _aaa.zip_ has inside: 
```
mem/enwik8.txt
mem/report.pdf
mem/report2.pdf
mem/thunk.bin
```

Now trying to extract a file (for example _mem/report2.pdf_) to _C:\TEMP\Unzip_ but without creating the "mem" subfolder. 
The goal is to get _C:\TEMP\Unzip\report.pdf_  .

Tried Command_4 sub, where I changed bResult for : 
`.bResult = .Extract ("C:\TEMP\Unzip\", "mem/report2.pdf"`

I get nothing.

Commented the lines : 
```
Set m_oExtractInMemory = m_oZip
Set m_oExtractInMemory = Nothing
```

I get file extracted but it is here _C:\TEMP\Unzip\mem\report.pdf_

Is there a way to ride of the "mem" subfolder ? 

Thanks :) 
Couin

**Comment by wqweto** [comment]
`Command3` is example of using in-memory operations with the memory stream class provided.

You can compress a file under a different name in the archive using the (optional) second parameter of `AddFile` method like this:
```vba
    With New cZipArchive
        .AddFile "D:\TEMP\aaa.pdf", "mem/report.pdf"
        .CompressArchive "D:\TEMP\aaa.zip"
    End With
```
This way `aaa.pdf` file on disk is stored as `report.pdf` file in `mem` directory in the archive.

If want to extract `report.pdf` to a custom folder on disk you can either use in-memory operations (i.e. extract to a byte-array and save it to whatever target file you want) or implement `BeforeExtract` event and modify `File` parameter like this:
```vba
Private WithEvents m_oExtractRename As cZipArchive

Private Sub Command8_Click()
    Set m_oExtractRename = New cZipArchive
    With m_oExtractRename
        .OpenArchive "D:\TEMP\aaa.zip"
        .Extract "D:\Temp"
    End With
End Sub

Private Sub m_oExtractRename_BeforeExtract(ByVal FileIdx As Long, File As Variant, SkipFile As Boolean, Cancel As Boolean)
    '--- change output path to D:\Temp
    File = "D:\Temp\" & Mid$(File, InStrRev(File, "\") + 1)
End Sub
```

**Comment by CouinCouin** [comment]
Hi wqweto, 

Thanks a lot, just quicky tried with the solution from your "Edit" and look working like desired :)

And yes, it's seems to be the best method, as well ad target folder can be different between files from inside the zip archive.

See ya :)
