### ISSUE TITLE
Extract File From Resource File

### ISSUE THREAD

**Issue by cyberzilla** [wqweto/ZipArchive#30]
I have tried extracting the test.zip file using the file path, and it succeeded in extracting all the files with all their contents, 
```
With New cZipArchive
    .OpenArchive Text1.Text 'test.zip
    .Extract App.Path & "\test", Password:="test123"
End With
```

but when I put the test.zip file into the resource file, and tried to extract it, only one file was extracted, how do I solve this?
```
Dim bytResourceData() As Byte
    bytResourceData = LoadResData(404, "CUSTOM")
  
With New cZipArchive
    .OpenArchive bytResourceData
    .Extract App.Path & "\test", Password:="test123"
End With
```
Thanks @wqweto

**Comment by wqweto** [comment]
Just tested this w/ an encrypted archive and the sample code works here.

One thing that might trip you up is if `App.Path & "\test"` folder does not exists but there is a filename `test` in the zip archive then it will only extract this `test` file into `App.Path` folder which might be unexpected. This feature is introduced in the latest release so to be able to easily extract single file from the zip archive.

**Comment by cyberzilla** [comment]
I have tested the extraction directly from the IDE, and it works. However, when I compile it into a .exe, only one file is extracted. I have tried using `Msgbox UBound(bytResourceData)` to debug the issue, and it appears that there is a difference of **2 bytes** between the IDE and the executable

**Comment by cyberzilla** [comment]
Apologies, maybe this is off-topic, but it seems that this case is similar to what's discussed [here](https://www.vbforums.com/showthread.php?891620-Vb6-res-file-size-error-DWord-Alignment-of-VB-Resource-File-Entries)

**Comment by wqweto** [comment]
Yes, zero padding on binary resources (to DWORD boudary) would be a problem because zip format stores its Central Directory at the end of the file but the sample code still works here w/ zero padding too because when Central Directory is missing (not found in this case) cZipArchive class tries to locate each file entry in the archive by scanning data from the start i.e. without reading Central Directory.

It all depends on the original compressor the zip archive is created with to populate each entry's Local Header correctly so that fallback strategy to work when needed -- 7-zip produces zip archives which work ok w/ fallback strategy.

**Comment by cyberzilla** [comment]
I have solved the problem. First, I converted the result of the zip file into a base64 string. Then, I embedded that string into a resource file and extracted it again, and it **worked**.

```
Dim baData() As Byte
baData = B64.DecodeArr(StrConv(LoadResData("B64", "CUSTOM"), vbUnicode))
With New cZipArchive
    .OpenArchive baData
    .Extract txtPath.Text, Password:=txtPass.Text
End With
```

i have test with .InflateBase64 with add `ZIP_INFLATE = 1`
```
Dim baOutput() as byte
With New cZipArchive
If .InflateBase64(StrConv(LoadResData("B64", "CUSTOM"), vbUnicode), baOutput) Then
    .OpenArchive baOutput
    .Extract txtPath.Text, Password:=txtPass.Text
End If
End With
```

But, it turns out that nothing happened, or did I miss something?

**Comment by cyberzilla** [comment]
Sorry, perhaps this question is off-topic. Can this class be used to access specific files within a zip file? For example, inside the byte array representing the zip file, there are several files that I want to use in my application. Is it possible to access those files directly without having to extract the entire zip file?

**Comment by wqweto** [comment]
Btw, you can extract individual files with something like
```
    .Extract txtPath.Text, Filter:="MyFile.txt", Password:=txtPass.Text
```

**Comment by cyberzilla** [comment]
Instead of using `loadResData`, I have found a very useful user control to attach binary data from [here](https://github.com/thetrik/ctlBinData), and combined it with `cZipArchive`. The result is exactly as expected.
