### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by antoninononooono** [wqweto/ZipArchive#32]
When I press the Command 2 button in your sample code and use 4 files which are altogether around 20 GB, I get an out of memory error in WriteBinary file.

    Public Sub WriteBinaryFile(sFile As String, baData() As Byte)
        Dim hFile           As Long
        Dim dwDummy         As Long
    
        hFile = CreateFile(sFile, GENERIC_WRITE, 0, 0, CREATE_ALWAYS, 0, 0)
        Call APIWriteFile(hFile, baData(0), UBound(baData) + 1, dwDummy, 0)
        Call CloseHandle(hFile)
    End Sub

Can we handle this in chunks perhaps?

**Comment by wqweto** [comment]
You can look at repo's README for class sample usage. For instance this will work with your large files
```
With New cZipArchive
    .AddFile "C:\Path\To\your_big_file1.dat"
    .AddFile "C:\Path\To\your_big_file2.dat"
    .AddFile "C:\Path\To\your_big_file3.dat"
    .AddFile "C:\Path\To\your_big_file4.dat"
    .CompressArchive App.Path & "\my_20gb_archive.zip"
End With
```

The class allows compressing in-memory into byte-arrays without hitting the disk and this sample code is what you re looking at. Of course this cannot compress 20GB of data in-memory so it's not a viable option for your use-case.

**Comment by antoninononooono** [comment]
Sorry, I don't understand it yet.
You say: "For instance this will work with your large files" and then you show cZipArchive.cls.
But then you say that this will will not work for me.

**Comment by wqweto** [comment]
Try it without in-memory operations i.e. don’t use byte-arrays for target of compression and don’t use WriteBinaryFile procedure.

Just use the snippet above without any other complications you found out in an uentioned test file in the repo. 

Repo’s README has sample code for most every common use-case you might have need for.

**Comment by antoninononooono** [comment]
Thank you. There seems to be some misunderstanding. 

I have google "Repo's README wqweto ASM ZIP", but even google does not find it.
I just don't understand what you mean. 
Also, I have not done anything special. I just clicked "<> Download", the "Zip", and I opened the files that were in this. 

Are you talking about something else?

**Comment by wqweto** [comment]
There is a README.md file in the ZIP you downloaded. You can directly view it here on github site by going to repo’s root page at https://github.com/wqweto/ZipArchive

All the useful sample code is there formatted in code sections. Almost every repo on github has a welcoming README file to explain how thing work.

**Comment by antoninononooono** [comment]
Thank you. I understood it now.
