### ISSUE TITLE
cZipArchive.Extract: support OutputTarget as vbLong, treat as naked pointer

### ISSUE THREAD

**Issue by tannerhelland** [wqweto/ZipArchive#8]
This is an esoteric request, so feel free to disregard and I will simply muck up my own cZipArchive copy to implement. ;)

Because large array allocations are especially expensive in VB, I would prefer to simply reuse a single large destination buffer when extracting a series of sequential files.  This is especially useful in my OpenRaster use-case, as I just need to extract PNG bytes via cZipArchive, then immediately decode it into a usable image buffer (and discard the original PNG stream).  It would save me a ton of allocation time to take the approach of, "find largest extracted size, prep single buffer at that size, re-use for all PNG extractions" vs the current approach of allocating new memory for each temporary Extract() output buffer.

Obviously, cZipArchive supporting a naked long as extraction target would require some amount of trust that the caller has properly read .Size property and allocated accordingly.  Not sure if this is desirable or not in a class designed for general use.

An alternate implementation could be a new optional parameter in Extract(), something to the effect of "only resize OutputTarget array if it's too small for this extraction", but this adds complexity on cZipArchive's end and the same problems persist - e.g. the caller still needs to confirm .Size to understand the output.  That's why I thought this implementation (passing a naked pointer) may be preferable.

(Actually there are other use-cases too, e.g. the caller could pass a pointer to something like a memory-mapped file view, which otherwise would require extra steps to "wrap" that bare pointer in a VB array.)

**Comment by wqweto** [comment]
As far as I understand you want to skip [output array resizing](https://github.com/wqweto/ZipArchive/blob/master/src/cZipArchive.cls#L1299) at line 1299
```
                If IsArray(OutputTarget) And .Size > 0 Then
                    ReDim OutputTarget(0 To .Size - 1) As Byte
                End If
```

Another strategy altogether is to implement VFS stream over your oversized buffer with naked pointer arithmetics and all. Check out sample [`cMemoryStream.cls`](https://github.com/wqweto/ZipArchive/blob/master/test/basic/cMemoryStream.cls) for all the `VszXxx` function-prototypes (below `VFS interface` comment) as expected to be impl by your stream class.

For `OutputTarget` I suppose you can even skip `VfsReadFile` impl as it will never be called from `Extract`.

**Comment by tannerhelland** [comment]
Apologies again for taking so long to revisit this.

After many rounds of perf-testing, the easiest solution proved to be just bypassing the need for .Extract() calls when possible.  Most OpenRaster exporters write uncompressed layer PNGs to the zip container - a smart decision, since PNGs are already 90+% deflate'd, and another deflate pass on top gains little but takes forever.

So I just hacked together a small ["peek"-like function](https://github.com/tannerhelland/PhotoDemon/blob/5180d076c85eed298d95a7079a376bb68e41243c/Classes/cZipArchive.cls#L1201) to return the file offset, compression state, and compressed/original size of individual archive entries.  If PNG files are uncompressed in the archive, [I can just point the PNG decoder at their offset](https://github.com/tannerhelland/PhotoDemon/blob/5180d076c85eed298d95a7079a376bb68e41243c/Classes/pdOpenRaster.cls#L326) and parse them directly from disk, skipping the Extract stage entirely.

For the few bad ORA writers who *do* store deflated PNGs, existing .Extract() function still works fine!  I may still drop in the new cBufferStream implementation you so helpfully provided, but profiling shows that time spent in inflate() far outweighs time spent in safearray allocation, so I probably fell victim to "premature optimization is the root of all evil" by targeting allocation perf first.   *(shrugs sheepishly)*

Thank you again for the new example code in cBufferStream.  I hope others find it useful too!
