### ISSUE TITLE
ZIP_DEFLATE conditional compilation to mirror ZIP_INFLATE?

### ISSUE THREAD

**Issue by tannerhelland** [wqweto/ZipArchive#9]
In https://github.com/wqweto/ZipArchive/commit/2421dda691c9140e826361be903a8ae13446d48d, low-level Inflate() wrappers were made accessible to outside callers - a great idea for VB6 devs looking to drop a zlibwapi dependency.

Does it make sense to do something similar for low-level Deflate() wrappers?  Your great contribution to [VB6 compression tester](https://github.com/tannerhelland/VB6-Compression/blob/master/pdCompressZThunk.cls) already provides a possible implementation, as I recall.

**Comment by wqweto** [comment]
Decided to impl `Deflate` under ZIP_INFLATE conditional compilation in https://github.com/wqweto/ZipArchive/commit/4612740330706e7f4c86bab63d435185007ef700

Turned out w/o base64 counterpart as there is no base64 encoding routing "for free" in class already.

**Comment by tannerhelland** [comment]
+1 looks great, thank you!

Just sent a small PR for base64 as the symmetry of this class is lovely and I'd hate to see it ruined...  ;)

Thanks as always for another very fast resolution.
